<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="MAIN" Id="{8f63f011-6378-4f32-beaf-4437ace2efcc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	myBoolean : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Modbus receive *)
//p_ModbusRx_OutputReg();
p_ModbusRx_OutputCoils();
p_ModbusRx_PLCMemory();

p_XLegacyPLCModbus();

(* 	HARD-WIRED I/O UPDATE
	Update IO 
*)


(* 	RESOLVE LOGIC
	Device Control & Monitoring 
*)


//p_TurboSup();
p_MPSSup();

(* 	HARD-WIRED I/O UPDATE
	Update IO 
*)


(* 	EPICS Tx UPDATE
	Modbus Map Receive
	IMPORTANT: This is the LAST subroutine to be called. 
*)
p_ModbusTx_InputCoils();
p_ModbusTx_OutputCoils();
p_ModbusTx_InputReg();
//p_ModbusTx_OutputReg();
p_ModbusTx_PLCMemory();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>