<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.26">
  <POU Name="p_EtherCATDiag" Id="{638320e6-8112-4f35-b44d-c25b584ef133}">
    <Declaration><![CDATA[PROGRAM p_EtherCATDiag
VAR
	fbEcatDiag1	:	FB_EcatDiag;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbEcatDiag1(i_AMSNetId:=g_aEcatMaster1, i_xFirstPass:=g_xFirstPass, q_xAllStatesGood=>g_xIOState);]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>