<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="p_SoftIOMap" Id="{29b29fdd-af3a-4f5d-979b-0ec37006ef74}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM p_SoftIOMap
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	(* Generic PLC Rail *)
//	i_iR46_40el3064s01c01 AT %I*: INT;
//	i_iR46_40el3064s01c02 AT %I*: INT;
//	i_iR46_40el3064s01c03 AT %I*: INT;
//	i_iR46_40el3064s01c04 AT %I*: INT;


//	i_xR46_40el1008s02c04 AT %I*: BOOL;
//	i_xR46_40el1008s02c05 AT %I*: BOOL;
//	i_xR46_40el1008s02c06 AT %I*: BOOL;
//	i_xR46_40el1008s02c07 AT %I*: BOOL;
//	i_xR46_40el1008s02c08 AT %I*: BOOL;

    i_xR47_32kl2794s01c01:= q_xMFX_LENS_MPSOK; //AT %Q*: BOOL;
//	q_xR46_40el2008s03c02 AT %Q*: BOOL;
//	q_xR46_40el2008s03c03 AT %Q*: BOOL;
//	q_xR46_40el2008s03c04 AT %Q*: BOOL;
//	q_xR46_40el2008s03c05 AT %Q*: BOOL;
//	q_xR46_40el2008s03c06 AT %Q*: BOOL;
//	q_xR46_40el2008s03c07 AT %Q*: BOOL;
//	q_xR46_40el2008s03c08 AT %Q*: BOOL;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>